/* =========================================================
   Nendu Cloud · js/manifest.js
   The published library of this drive — files that live in the
   repository under /files/<category>/<name>, served by GitHub
   Pages next to the site. Regenerated by `npm run build:manifest`.

   Local drag & drop uploads never appear here on purpose: they
   stay inside this browser's IndexedDB.
   ========================================================= */

window.CLOUD_MANIFEST = [];
