const { chromium } = require('playwright-core');
const BASE='https://nendrandukes-bit.github.io/Storage';
let pass=0,fail=0; const ok=(n,c,e)=>{c?(pass++,console.log('  ✔ '+n+(e?'  '+e:''))):(fail++,console.log('  ✘ '+n+(e?'  → '+e:'')));};
(async()=>{
const b=await chromium.launch({executablePath:'/home/user/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox']});
const ctx=await b.newContext({viewport:{width:1560,height:1000},deviceScaleFactor:2,acceptDownloads:true});
const p=await ctx.newPage(); const errs=[],bad=[];
p.on('pageerror',e=>errs.push('pageerror: '+e.message)); p.on('console',m=>{if(m.type()==='error')errs.push('console: '+m.text())});
p.on('response',r=>{if(r.status()>=400)bad.push(r.status()+' '+r.url())});
await p.goto(BASE+'/',{waitUntil:'load',timeout:45000});
await p.waitForFunction(()=>document.querySelectorAll('#grid .card').length>=7,null,{timeout:20000});
ok('7 published demo files render', (await p.$$('#grid .card')).length===7);
const nav=await p.$$eval('#nav .nav-item[data-cat]',e=>Object.fromEntries(e.map(x=>[x.dataset.cat,x.querySelector('.nav-count').textContent])));
ok('every category has content', ['photos','videos','docs','apk','audio','archives'].every(k=>nav[k]!=='0'), JSON.stringify(nav));
await p.fill('#search','zip'); await p.waitForTimeout(400);
ok('search finds published archive by type', /nendu-drive-v1\.2\.zip/.test(await p.textContent('#grid')));
await p.click('#grid .card'); await p.waitForSelector('#pv-viewer .zip-list li',{timeout:15000});
const z=await p.$$eval('#modal .zip-list li',n=>n.map(x=>x.textContent.trim()));
ok('published zip lists its real entries', z.length===3, z.join(' | '));
await p.waitForFunction(()=>/[a-f0-9]{64}/.test(document.querySelector('#pv-extras .hashbox').textContent),null,{timeout:20000});
ok('published file SHA-256 computed', true);
await p.keyboard.press('Escape');
await p.click('#nav .nav-item[data-cat="videos"]'); await p.waitForTimeout(500);
ok('video thumbnail published', (await p.$$eval('#grid .card .thumb img',n=>n.length))===1);
await p.click('#grid .card'); await p.waitForSelector('#pv-viewer video',{timeout:15000});
const st=await p.evaluate(async()=>{const v=document.querySelector('#pv-viewer video');try{v.muted=true;await v.play();}catch(e){return 'blocked';}await new Promise(r=>setTimeout(r,600));return v.currentTime>0?'playing':'paused';});
ok('published video streams + plays', st==='playing', st);
await p.keyboard.press('Escape');
await p.click('#nav .nav-item[data-cat="docs"]'); await p.waitForTimeout(400);
await p.click('#grid .card:has-text("trip-log.md")'); await p.waitForSelector('#modal .md h1',{timeout:15000});
ok('published markdown renders', (await p.textContent('#modal .md h1')).length>3);
await p.waitForFunction(()=>document.querySelectorAll('#pv-tags .tag').length>0,null,{timeout:8000});
ok('tags from the manifest are clickable', (await p.$$eval('#pv-tags .tag',n=>n.map(x=>x.textContent)).join(',')));
await p.keyboard.press('Escape');
const [dl]=await Promise.all([p.waitForEvent('download',{timeout:20000}), p.click('#grid .card:has-text("trip-log.md") .c-actions button[aria-label="Download"]')]);
const fsx=require('fs'); const t='/home/user/.live-dl'; await dl.saveAs(t);
ok('published download byte-identical', fsx.readFileSync(t,'utf8')===fsx.readFileSync('/home/user/files/docs/trip-log.md','utf8'), dl.suggestedFilename());
fsx.unlinkSync(t);
await p.click('#nav .nav-item[data-cat="apk"]'); await p.waitForTimeout(400);
await p.click('#grid .card'); await p.waitForSelector('#pv-viewer .hex',{timeout:15000});
ok('APK panel shows sideload guidance + header', /Android package ready to sideload/.test(await p.textContent('#pv-viewer')));
await p.keyboard.press('Escape'); await p.waitForTimeout(400);
await p.screenshot({path:'/home/user/shots/LIVE-2.png'});
await p.fill('#search','drone'); await p.waitForTimeout(500);
await p.screenshot({path:'/home/user/shots/LIVE-search.png'});
await p.fill('#search','');
await b.close();
ok('no failed requests on Pages', bad.length===0, bad.slice(0,3).join(' | '));
ok('no page/console errors', errs.length===0, errs.slice(0,3).join(' | '));
console.log('\n'+(fail?'✘':'✔')+` ${pass} passed, ${fail} failed`); process.exit(fail?1:0);
})().catch(e=>{console.log('ERR',e.stack);process.exit(2)});
