const { chromium } = require('playwright-core');
const BASE='https://nendrandukes-bit.github.io/Storage';
(async()=>{
const b=await chromium.launch({executablePath:'/home/user/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox']});
const ctx=await b.newContext({viewport:{width:1560,height:1010},deviceScaleFactor:2});
const p=await ctx.newPage();
await p.goto(BASE+'/?v='+Date.now(),{waitUntil:'load'});
await p.waitForFunction(()=>document.querySelectorAll('#grid .card').length===7,null,{timeout:20000});
await p.waitForTimeout(1500);
await p.screenshot({path:'/home/user/shots/LIVE-home.png'});
await p.fill('#search','ridge'); await p.waitForTimeout(700);
await p.screenshot({path:'/home/user/shots/LIVE-search.png'});
await p.fill('#search',''); await p.waitForTimeout(400);
await p.click('#grid .card:has-text("drone-flyover.mp4")');
await p.waitForSelector('#pv-viewer video'); await p.waitForTimeout(2500);
await p.screenshot({path:'/home/user/shots/LIVE-video.png'});
await p.keyboard.press('Escape'); await p.waitForTimeout(300);
await p.click('#grid .card:has-text("nendu-drive-beta.apk")');
await p.waitForSelector('#pv-viewer .hex'); await p.waitForTimeout(1500);
await p.screenshot({path:'/home/user/shots/LIVE-apk.png'});
await p.keyboard.press('Escape');
const m=await b.newContext({viewport:{width:430,height:910},deviceScaleFactor:2});
const mp=await m.newPage();
await mp.goto(BASE+'/?m='+Date.now(),{waitUntil:'load'});
await mp.waitForFunction(()=>document.querySelectorAll('#grid .card').length===7,null,{timeout:20000});
await mp.waitForTimeout(1200);
await mp.screenshot({path:'/home/user/shots/LIVE-mobile.png'});
await b.close(); console.log('ok');
})().catch(e=>console.log('ERR',e.message));
